1. The company wishes to clarify whether there is any increase in sales after
stepping into digital marketing.
2. The company needs to check whether there is any dependency between the
features “Region” and “Manager”.

In [1]:
import pandas as pd
import numpy as np

# Reading the dataset into python

In [2]:
data=pd.read_csv(r'C:\Users\Abhilash\Downloads\Sales_add.csv')

In [3]:
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [4]:
data.isna().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [5]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

# 1.Checking whether there is any increase in sales after stepping into digital marketing

### Ho:-sales before digital marketing=sales after digital marketing 

### H1:-sales before digital marketing < sales after digital marketing

In [6]:
from scipy import stats
data[['Sales_before_digital_add(in $)','Sales_After_digital_add(in $)']].describe()
ttest,pval=stats.ttest_rel(data['Sales_before_digital_add(in $)'],data['Sales_After_digital_add(in $)'])
print(pval)
if pval<0.05:
    print('reject null hypothesis')
else:
    print('accept null hypothesis')

6.336667004575778e-11
reject null hypothesis


By doing the hypothesis testing we can understand that the sales before digital marketing is not equal to sales after digital marketing.it is increasing after the digital marketing.because the p value nearly equal to zero and we reject the null hypothesis.so that the sales have increased

# 2.Checking the dependency between the features Region and Manager

### H0 :-There is no relationship between Region and Manager

### H1 :-There is a relationship between Region and Manager

In [7]:
contingency_table=pd.crosstab(data["Region"],data["Manager"])
print('contingency_table :-\n',contingency_table)
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)
b=stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between Region and Manager")
else:
    print("Retain H0,There is no relationship between Region and Manager")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between Region and Manager")
else:
    print("Retain H0,There is no relationship between Region and Manager")

contingency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1
Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]
Expected Values :-
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
Degree of Freedom:- 1
chi-square statistic:- 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139
Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139
Retain H0,There is no relationship between Region and Manager
Retain H0,There is no relationship between Region and Manager


Observation :- From this chi squre test we can conclude that the region and manager have no relation with each other.